-- ============================================================
-- Advanced Features: Reviews, Wishlist, Brands, Subcategories, Multi-Language
-- ============================================================

-- Brands table
CREATE TABLE IF NOT EXISTS `brands` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL,
    `slug` VARCHAR(120) NOT NULL UNIQUE,
    `status` ENUM('active','inactive') DEFAULT 'active',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Subcategories table
CREATE TABLE IF NOT EXISTS `subcategories` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `category_id` INT NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    `slug` VARCHAR(120) NOT NULL,
    `status` ENUM('active','inactive') DEFAULT 'active',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE CASCADE,
    UNIQUE KEY `unique_subcat_slug` (`category_id`, `slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Add brand_id and subcategory_id to products
ALTER TABLE `products`
    ADD COLUMN `brand_id` INT DEFAULT NULL AFTER `category_id`,
    ADD COLUMN `subcategory_id` INT DEFAULT NULL AFTER `brand_id`,
    ADD COLUMN `is_featured` TINYINT(1) DEFAULT 0 AFTER `stock`,
    ADD COLUMN `discount_percent` DECIMAL(5,2) DEFAULT 0 AFTER `is_featured`,
    ADD COLUMN `sales_count` INT DEFAULT 0 AFTER `discount_percent`,
    ADD FOREIGN KEY (`brand_id`) REFERENCES `brands`(`id`) ON DELETE SET NULL,
    ADD FOREIGN KEY (`subcategory_id`) REFERENCES `subcategories`(`id`) ON DELETE SET NULL;

-- Reviews table
CREATE TABLE IF NOT EXISTS `reviews` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `product_id` INT NOT NULL,
    `user_id` INT NOT NULL,
    `rating` TINYINT(1) NOT NULL CHECK (`rating` BETWEEN 1 AND 5),
    `comment` TEXT NOT NULL,
    `status` ENUM('active','hidden') DEFAULT 'active',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
    UNIQUE KEY `unique_product_user_review` (`product_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Wishlist table
CREATE TABLE IF NOT EXISTS `wishlist` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL,
    `product_id` INT NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE CASCADE,
    UNIQUE KEY `unique_user_product_wishlist` (`user_id`, `product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Site translations table
CREATE TABLE IF NOT EXISTS `site_translations` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `lang_code` VARCHAR(5) NOT NULL,
    `translation_key` VARCHAR(150) NOT NULL,
    `translation_value` TEXT NOT NULL,
    UNIQUE KEY `unique_lang_key` (`lang_code`, `translation_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Sample brands
INSERT INTO `brands` (`name`, `slug`, `status`) VALUES
('Generic', 'generic', 'active'),
('Premium', 'premium', 'active'),
('Budget', 'budget', 'active');

-- Sample subcategories for existing categories (category_id 1 assumed)
INSERT INTO `subcategories` (`category_id`, `name`, `slug`, `status`) VALUES
(1, 'Electronics', 'electronics', 'active'),
(1, 'Accessories', 'accessories', 'active'),
(1, 'Clothing', 'clothing', 'active');

-- ============================================================
-- Hindi Translations (EN keys)
-- ============================================================
INSERT INTO `site_translations` (`lang_code`, `translation_key`, `translation_value`) VALUES
-- Navbar
('hi', 'home', 'होम'),
('hi', 'products', 'उत्पाद'),
('hi', 'categories', 'श्रेणियाँ'),
('hi', 'cart', 'कार्ट'),
('hi', 'account', 'खाता'),
('hi', 'dashboard', 'डैशबोर्ड'),
('hi', 'my_orders', 'मेरे ऑर्डर'),
('hi', 'my_returns', 'मेरे रिटर्न'),
('hi', 'my_wishlist', 'मेरी विशलिस्ट'),
('hi', 'profile', 'प्रोफ़ाइल'),
('hi', 'logout', 'लॉगआउट'),
('hi', 'login', 'लॉगिन'),
('hi', 'sign_up', 'साइन अप'),
('hi', 'search', 'खोजें'),
('hi', 'search_products', 'उत्पाद खोजें...'),
-- Footer
('hi', 'quick_links', 'त्वरित लिंक'),
('hi', 'contact_us', 'संपर्क करें'),
('hi', 'all_rights_reserved', 'सर्वाधिकार सुरक्षित'),
-- Products
('hi', 'add_to_cart', 'कार्ट में जोड़ें'),
('hi', 'view_details', 'विवरण देखें'),
('hi', 'in_stock', 'स्टॉक में'),
('hi', 'out_of_stock', 'स्टॉक में नहीं'),
('hi', 'related_products', 'संबंधित उत्पाद'),
('hi', 'estimated_delivery', 'अनुमानित डिलीवरी'),
('hi', 'within_days', 'दिनों के भीतर'),
('hi', 'delivered', 'डिलीवर हो गया'),
('hi', 'quantity', 'मात्रा'),
('hi', 'price', 'मूल्य'),
('hi', 'description', 'विवरण'),
('hi', 'features', 'विशेषताएँ'),
('hi', 'high_quality_product', 'उच्च गुणवत्ता वाला उत्पाद'),
('hi', 'fast_shipping', 'तेज़ शिपिंग उपलब्ध'),
('hi', 'return_policy', '7 दिन की रिटर्न पॉलिसी'),
('hi', 'secure_payment', 'सुरक्षित भुगतान'),
-- Cart
('hi', 'shopping_cart', 'शॉपिंग कार्ट'),
('hi', 'subtotal', 'उप-कुल'),
('hi', 'shipping', 'शिपिंग'),
('hi', 'free', 'मुफ़्त'),
('hi', 'total', 'कुल'),
('hi', 'proceed_to_checkout', 'चेकआउट पर जाएं'),
('hi', 'continue_shopping', 'खरीदारी जारी रखें'),
('hi', 'empty_cart', 'आपका कार्ट खाली है'),
('hi', 'start_shopping', 'खरीदारी शुरू करें'),
('hi', 'free_shipping_msg', '₹500 से अधिक के ऑर्डर पर मुफ़्त शिपिंग'),
('hi', 'remove', 'हटाएं'),
('hi', 'update', 'अपडेट'),
-- Checkout
('hi', 'checkout', 'चेकआउट'),
('hi', 'shipping_info', 'शिपिंग जानकारी'),
('hi', 'full_name', 'पूरा नाम'),
('hi', 'email', 'ईमेल'),
('hi', 'mobile_number', 'मोबाइल नंबर'),
('hi', 'address', 'पता'),
('hi', 'city', 'शहर'),
('hi', 'state', 'राज्य'),
('hi', 'pincode', 'पिनकोड'),
('hi', 'payment_method', 'भुगतान विधि'),
('hi', 'cod', 'कैश ऑन डिलीवरी (COD)'),
('hi', 'pay_online', 'ऑनलाइन भुगतान (Razorpay)'),
('hi', 'place_order', 'ऑर्डर दें'),
('hi', 'order_summary', 'ऑर्डर सारांश'),
('hi', 'items', 'आइटम'),
('hi', 'total_amount', 'कुल राशि'),
('hi', 'pay_now', 'अभी भुगतान करें'),
('hi', 'use_current_location', 'मेरा वर्तमान स्थान उपयोग करें'),
-- Orders
('hi', 'my_orders', 'मेरे ऑर्डर'),
('hi', 'order_number', 'ऑर्डर नंबर'),
('hi', 'order_date', 'ऑर्डर तिथि'),
('hi', 'total_amount', 'कुल राशि'),
('hi', 'payment_method', 'भुगतान विधि'),
('hi', 'order_status', 'ऑर्डर स्थिति'),
('hi', 'order_details', 'ऑर्डर विवरण'),
('hi', 'view_details', 'विवरण देखें'),
('hi', 'no_orders', 'कोई ऑर्डर नहीं मिला'),
('hi', 'back_to_orders', 'ऑर्डर पर वापस'),
('hi', 'shipping_address', 'शिपिंग पता'),
('hi', 'est_delivery', 'अनुमानित डिलीवरी'),
-- Login / Signup
('hi', 'login_to_account', 'अपने खाते में लॉगिन करें'),
('hi', 'create_account', 'खाता बनाएं'),
('hi', 'welcome_back', 'वापसी पर स्वागत'),
('hi', 'already_have_account', 'पहले से खाता है?'),
('hi', 'dont_have_account', 'खाता नहीं है?'),
('hi', 'forgot_password', 'पासवर्ड भूल गए?'),
-- Profile
('hi', 'my_profile', 'मेरी प्रोफ़ाइल'),
('hi', 'update_profile', 'प्रोफ़ाइल अपडेट करें'),
('hi', 'member_since', 'सदस्य बने'),
('hi', 'last_updated', 'अंतिम अपडेट'),
-- Reviews
('hi', 'customer_reviews', 'ग्राहक समीक्षाएँ'),
('hi', 'write_review', 'समीक्षा लिखें'),
('hi', 'your_rating', 'आपकी रेटिंग'),
('hi', 'your_review', 'आपकी समीक्षा'),
('hi', 'submit_review', 'समीक्षा सबमिट करें'),
('hi', 'edit_review', 'समीक्षा संपादित करें'),
('hi', 'delete_review', 'समीक्षा हटाएं'),
('hi', 'review_submitted', 'समीक्षा सफलतापूर्वक सबमिट हुई'),
('hi', 'review_updated', 'समीक्षा अपडेट हुई'),
('hi', 'review_deleted', 'समीक्षा हटाई गई'),
('hi', 'review_placeholder', 'इस उत्पाद के बारे में अपनी राय लिखें...'),
('hi', 'only_purchased', 'केवल खरीदे गए उत्पादों की समीक्षा कर सकते हैं'),
('hi', 'already_reviewed', 'आपने पहले ही इस उत्पाद की समीक्षा कर दी है'),
('hi', 'no_reviews', 'अभी तक कोई समीक्षा नहीं'),
('hi', 'based_on_reviews', 'समीक्षाओं पर आधारित'),
-- Wishlist
('hi', 'add_to_wishlist', 'विशलिस्ट में जोड़ें'),
('hi', 'remove_from_wishlist', 'विशलिस्ट से हटाएं'),
('hi', 'my_wishlist', 'मेरी विशलिस्ट'),
('hi', 'empty_wishlist', 'आपकी विशलिस्ट खाली है'),
('hi', 'move_to_cart', 'कार्ट में ले जाएं'),
('hi', 'added_to_wishlist', 'विशलिस्ट में जोड़ा गया'),
('hi', 'removed_from_wishlist', 'विशलिस्ट से हटाया गया'),
('hi', 'already_in_wishlist', 'पहले से विशलिस्ट में है'),
-- Filters
('hi', 'filter_products', 'उत्पाद फ़िल्टर करें'),
('hi', 'all_categories', 'सभी श्रेणियाँ'),
('hi', 'all_brands', 'सभी ब्रांड'),
('hi', 'price_range', 'मूल्य सीमा'),
('hi', 'min_rating', 'न्यूनतम रेटिंग'),
('hi', 'availability', 'उपलब्धता'),
('hi', 'in_stock', 'स्टॉक में'),
('hi', 'out_of_stock', 'स्टॉक में नहीं'),
('hi', 'sort_by', 'क्रमबद्ध करें'),
('hi', 'latest', 'नवीनतम'),
('hi', 'best_selling', 'सर्वाधिक बिकने वाले'),
('hi', 'featured', 'विशेष'),
('hi', 'discounted', 'छूट वाले'),
('hi', 'price_low_high', 'मूल्य: कम से अधिक'),
('hi', 'price_high_low', 'मूल्य: अधिक से कम'),
('hi', 'highest_rated', 'सर्वोच्च रेटेड'),
('hi', 'most_popular', 'सबसे लोकप्रिय'),
('hi', 'az', 'A-Z'),
('hi', 'za', 'Z-A'),
('hi', 'no_products_found', 'कोई उत्पाद नहीं मिला'),
('hi', 'results_found', 'परिणाम मिले'),
-- Returns
('hi', 'return_product', 'उत्पाद वापस करें'),
('hi', 'my_returns', 'मेरे रिटर्न'),
('hi', 'return_requested', 'रिटर्न अनुरोध'),
('hi', 'under_review', 'समीक्षा में'),
('hi', 'approved', 'स्वीकृत'),
('hi', 'rejected', 'अस्वीकृत'),
-- Admin
('hi', 'admin_panel', 'एडमिन पैनल'),
('hi', 'dashboard', 'डैशबोर्ड'),
('hi', 'manage_orders', 'ऑर्डर प्रबंधन'),
('hi', 'manage_products', 'उत्पाद प्रबंधन'),
('hi', 'manage_users', 'उपयोगकर्ता प्रबंधन'),
('hi', 'manage_categories', 'श्रेणी प्रबंधन'),
('hi', 'manage_returns', 'रिटर्न प्रबंधन'),
('hi', 'view_site', 'साइट देखें'),
-- Common
('hi', 'save', 'सहेजें'),
('hi', 'cancel', 'रद्द करें'),
('hi', 'confirm', 'पुष्टि करें'),
('hi', 'yes', 'हाँ'),
('hi', 'no', 'नहीं'),
('hi', 'loading', 'लोड हो रहा है'),
('hi', 'error', 'त्रुटि'),
('hi', 'success', 'सफल'),
('hi', 'warning', 'चेतावनी'),
('hi', 'no_results', 'कोई परिणाम नहीं'),
('hi', 'days', 'दिन'),

-- English Translations (same keys)
('en', 'home', 'Home'),
('en', 'products', 'Products'),
('en', 'categories', 'Categories'),
('en', 'cart', 'Cart'),
('en', 'account', 'Account'),
('en', 'dashboard', 'Dashboard'),
('en', 'my_orders', 'My Orders'),
('en', 'my_returns', 'My Returns'),
('en', 'my_wishlist', 'My Wishlist'),
('en', 'profile', 'Profile'),
('en', 'logout', 'Logout'),
('en', 'login', 'Login'),
('en', 'sign_up', 'Sign Up'),
('en', 'search', 'Search'),
('en', 'search_products', 'Search products...'),
('en', 'quick_links', 'Quick Links'),
('en', 'contact_us', 'Contact Us'),
('en', 'all_rights_reserved', 'All rights reserved'),
('en', 'add_to_cart', 'Add to Cart'),
('en', 'view_details', 'View Details'),
('en', 'in_stock', 'In Stock'),
('en', 'out_of_stock', 'Out of Stock'),
('en', 'related_products', 'Related Products'),
('en', 'estimated_delivery', 'Estimated Delivery'),
('en', 'within_days', 'Within'),
('en', 'delivered', 'Delivered'),
('en', 'quantity', 'Quantity'),
('en', 'price', 'Price'),
('en', 'description', 'Description'),
('en', 'features', 'Features'),
('en', 'high_quality_product', 'High Quality Product'),
('en', 'fast_shipping', 'Fast Shipping Available'),
('en', 'return_policy', '7 Days Return Policy'),
('en', 'secure_payment', 'Secure Payment'),
('en', 'shopping_cart', 'Shopping Cart'),
('en', 'subtotal', 'Subtotal'),
('en', 'shipping', 'Shipping'),
('en', 'free', 'FREE'),
('en', 'total', 'Total'),
('en', 'proceed_to_checkout', 'Proceed to Checkout'),
('en', 'continue_shopping', 'Continue Shopping'),
('en', 'empty_cart', 'Your cart is empty'),
('en', 'start_shopping', 'Start Shopping'),
('en', 'free_shipping_msg', 'Free shipping on orders over ₹500'),
('en', 'remove', 'Remove'),
('en', 'update', 'Update'),
('en', 'checkout', 'Checkout'),
('en', 'shipping_info', 'Shipping Information'),
('en', 'full_name', 'Full Name'),
('en', 'email', 'Email'),
('en', 'mobile_number', 'Mobile Number'),
('en', 'address', 'Address'),
('en', 'city', 'City'),
('en', 'state', 'State'),
('en', 'pincode', 'Pincode'),
('en', 'payment_method', 'Payment Method'),
('en', 'cod', 'Cash on Delivery (COD)'),
('en', 'pay_online', 'Pay Online (Razorpay)'),
('en', 'place_order', 'Place Order'),
('en', 'order_summary', 'Order Summary'),
('en', 'items', 'Items'),
('en', 'total_amount', 'Total Amount'),
('en', 'pay_now', 'Pay Now'),
('en', 'use_current_location', 'Use My Current Location'),
('en', 'order_number', 'Order Number'),
('en', 'order_date', 'Order Date'),
('en', 'order_status', 'Order Status'),
('en', 'order_details', 'Order Details'),
('en', 'no_orders', 'No orders found'),
('en', 'back_to_orders', 'Back to Orders'),
('en', 'shipping_address', 'Shipping Address'),
('en', 'est_delivery', 'Estimated Delivery'),
('en', 'login_to_account', 'Login to your account'),
('en', 'create_account', 'Create Account'),
('en', 'welcome_back', 'Welcome Back'),
('en', 'already_have_account', 'Already have an account?'),
('en', 'dont_have_account', 'Don\'t have an account?'),
('en', 'forgot_password', 'Forgot Password?'),
('en', 'my_profile', 'My Profile'),
('en', 'update_profile', 'Update Profile'),
('en', 'member_since', 'Member Since'),
('en', 'last_updated', 'Last Updated'),
('en', 'customer_reviews', 'Customer Reviews'),
('en', 'write_review', 'Write a Review'),
('en', 'your_rating', 'Your Rating'),
('en', 'your_review', 'Your Review'),
('en', 'submit_review', 'Submit Review'),
('en', 'edit_review', 'Edit Review'),
('en', 'delete_review', 'Delete Review'),
('en', 'review_submitted', 'Review submitted successfully'),
('en', 'review_updated', 'Review updated'),
('en', 'review_deleted', 'Review deleted'),
('en', 'review_placeholder', 'Write your thoughts about this product...'),
('en', 'only_purchased', 'You can only review products you have purchased'),
('en', 'already_reviewed', 'You have already reviewed this product'),
('en', 'no_reviews', 'No reviews yet'),
('en', 'based_on_reviews', 'Based on'),
('en', 'add_to_wishlist', 'Add to Wishlist'),
('en', 'remove_from_wishlist', 'Remove from Wishlist'),
('en', 'empty_wishlist', 'Your wishlist is empty'),
('en', 'move_to_cart', 'Move to Cart'),
('en', 'added_to_wishlist', 'Added to wishlist'),
('en', 'removed_from_wishlist', 'Removed from wishlist'),
('en', 'already_in_wishlist', 'Already in wishlist'),
('en', 'filter_products', 'Filter Products'),
('en', 'all_categories', 'All Categories'),
('en', 'all_brands', 'All Brands'),
('en', 'price_range', 'Price Range'),
('en', 'min_rating', 'Minimum Rating'),
('en', 'availability', 'Availability'),
('en', 'sort_by', 'Sort By'),
('en', 'latest', 'Latest'),
('en', 'best_selling', 'Best Selling'),
('en', 'featured', 'Featured'),
('en', 'discounted', 'Discounted'),
('en', 'price_low_high', 'Price: Low to High'),
('en', 'price_high_low', 'Price: High to Low'),
('en', 'highest_rated', 'Highest Rated'),
('en', 'most_popular', 'Most Popular'),
('en', 'az', 'A-Z'),
('en', 'za', 'Z-A'),
('en', 'no_products_found', 'No products found'),
('en', 'results_found', 'results found'),
('en', 'return_product', 'Return Product'),
('en', 'under_review', 'Under Review'),
('en', 'approved', 'Approved'),
('en', 'rejected', 'Rejected'),
('en', 'admin_panel', 'Admin Panel'),
('en', 'manage_orders', 'Manage Orders'),
('en', 'manage_products', 'Manage Products'),
('en', 'manage_users', 'Manage Users'),
('en', 'manage_categories', 'Manage Categories'),
('en', 'manage_returns', 'Manage Returns'),
('en', 'view_site', 'View Site'),
('en', 'save', 'Save'),
('en', 'cancel', 'Cancel'),
('en', 'confirm', 'Confirm'),
('en', 'yes', 'Yes'),
('en', 'no', 'No'),
('en', 'loading', 'Loading'),
('en', 'error', 'Error'),
('en', 'success', 'Success'),
('en', 'warning', 'Warning'),
('en', 'no_results', 'No results'),
('en', 'days', 'Days');
